apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
data:
  password: {{ pluck .Values.global.env .Values.redis.password | first | default .Values.redis.password._default | b64enc }}
type: Opaque