---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
  annotations:
    "werf.io/fail-mode": IgnoreAndContinueDeployProcess
spec:
  replicas: {{ pluck .Values.global.env .Values.redis.sentinel.replicas | first | default .Values.redis.sentinel.replicas._default }}
  selector:
    matchLabels:
      app: redis-sentinel-proxy
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy
    spec:
      affinity:
      imagePullSecrets:
      - name: "registrysecret"
      initContainers:
      - name: wait-sentinel
{{ tuple "initimage" . | include "werf_container_image" | indent 8 }}
        command: [ '/bin/sh', '-c', "while ! nc -z rfr-redis 6379; do sleep 1; done" ]
      containers:
      - name: redis-sentinel-proxy
{{ tuple "flant_redis_sentinel_proxy" . | include "werf_container_image" | indent 10 }}
        command: ["/usr/local/bin/redis-sentinel-proxy", "-master", "mymaster", "-sentinel", "rfs-redis:26379"]
        ports:
        - containerPort: 9999
        livenessProbe:
          initialDelaySeconds: 40
          periodSeconds: 1
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
          exec:
            command: ["redis-cli", "-p", "9999", "ping"]
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 10
          exec:
            command: ["redis-cli", "-p", "9999", "ping"]
        resources:
          requests:
            cpu: {{ pluck .Values.global.env .Values.redis.proxy.resources.requests.cpu | first | default .Values.redis.proxy.resources.requests.cpu._default }}
            memory: {{ pluck .Values.global.env .Values.redis.proxy.resources.requests.memory | first | default .Values.redis.proxy.resources.requests.memory._default }}
          limits:
            memory: {{ pluck .Values.global.env .Values.redis.proxy.resources.limits.memory | first | default .Values.redis.proxy.resources.limits.memory._default }}