---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: redis
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: rfr-redis
  updatePolicy:
    updateMode: "Off"
