name: Build and deploy dev AWS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildAndDeploy2Dev:
    name: "Build and Deploy Dev"
    runs-on: self-hosted
    env:
      WERF_KUBE_CONTEXT: "main-aws"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: werf converge
        uses: werf/actions/converge@v1.2
        with:
          channel: alpha
          env: heyka-dev